# DAY 1

### Exercise 1: Given a string of odd length greater than 7, return a new string made of the middle three characters of a given String
Given:
str1 = "JhonDipPeta"
str2 = "JaSonAy"
Output:
Dip
Son

In [28]:
def Mid_three_word(str1):
    mid=len(str1)//2
    new_str=str1[mid-1:mid+2]
    
    return new_str

Mid_three_word(str2)

'Son'

### Exercise 2: Given two strings, s1 and s2, create a new string by appending s2 in the middle of s1
Given:
s1 = "Ault"
s2 = "Kelly"
Expected Output:
AuKellylt

In [30]:
def Appending_new_str_mid_of_s1(s1,s2):
    mid=len(s1)//2
    new_str=s1[:mid]+s2+s1[mid:]
    return new_str
Appending_new_str_mid_of_s1("Ault","Kelly")

'AuKellylt'

### Exercise 3: Arrange string characters such that lowercase letters should come first
Given:
str1 = PyNaTive
Output:
yaivePNT

In [32]:
def Arrange_Str_LowerCase_letr(str1):
    new_str_low=""
    new_str_upp=""
    for i in range(len(str1)):
        if str1[i].islower():
            new_str_low+=str1[i]
        else:
            new_str_upp+=str1[i]
    return new_str_low+new_str_upp
Arrange_Str_LowerCase_letr("PyNaTive")

'yaivePNT'

### Exercise 4: Find the last position of a substring “Emma” in a given string
Given: 
str1 = "Emma is a data scientist who knows Python. Emma works at google."
Output:
Last occurrence of Emma starts at index 43

In [37]:
def Find_Position_Sub(str1,word):
    
    return str1.rfind(word)
Find_Position_Sub("Emma is a data scientist who knows Python. Emma works at google.","Emma")
    

43

# DAY 2

### Exercise 1: Print First 10 natural numbers using while loop

In [39]:
i=1
while i<=10:
    print(i,sep=" ",end=" ")
    i+=1
    

1 2 3 4 5 6 7 8 9 10 

### 
### 1 
### 1 2 
### 1 2 3 
### 1 2 3 4 
### 1 2 3 4 5

In [42]:
def pattern(row):
    for i in range(1,row):
        for j in range(1,i+1):
            print(j,sep="",end=" ")
        print()
pattern(5)

1 
1 2 
1 2 3 
1 2 3 4 


### Exercise 3: Calculate the sum of all numbers from 1 to a given number


In [48]:
def Sum(num):
    sum=0
    for i in range(num+1):
        sum+=i
    return sum
Sum(10)

55

### Exercise 4: Write a program to print multiplication table of a given number

In [58]:
def Multiplication_table(num):
    for i in range(1,10+1):
        multy=i*num
        if i==10:
            print(f"{i} *  {num} = {multy}")
        else:
            print(f"{i}  *  {num} = {multy}")
Multiplication_table(4)

1  *  4 = 4
2  *  4 = 8
3  *  4 = 12
4  *  4 = 16
5  *  4 = 20
6  *  4 = 24
7  *  4 = 28
8  *  4 = 32
9  *  4 = 36
10 *  4 = 40


### Exercise 5: Display numbers from a list using loop

In [59]:
list1=[1,2,3,4,5,6,7]
for i in list1:
    print(i)

1
2
3
4
5
6
7


### Exercise 6: Count the total number of digits in a number

In [66]:
def count_digit(num):
    count=0
    while num!=0:
        count+=1
        num=num//10
    return count
num=100
count_digit(num)

3

### 5 4 3 2 1 
### 4 3 2 1 
#### 3 2 1 
#### 2 1 
#### 1

In [79]:
row=int(input("Enter Row Value:"))
for i in range(0,row):
    value=row-i
    for j in range(0,row-i):
        print(value,end=" ")
        value-=1
    print()

Enter Row Value:8
8 7 6 5 4 3 2 1 
7 6 5 4 3 2 1 
6 5 4 3 2 1 
5 4 3 2 1 
4 3 2 1 
3 2 1 
2 1 
1 


### Exercise 8: Print list in reverse order using a loop

In [82]:
list1=[1,2,3,4,5,6,7,8,9]
for i in range(len(list1)-1,-1,-1):
    print(list1[i],end=" ")

9 8 7 6 5 4 3 2 1 

### Exercise 9: Display numbers from -10 to -1 using for loop

In [89]:
for i in range(-10,0):
    print(i,end=" ")

-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

### Exercise 10: Use else block to display a message “Done” after successful execution of for loop

In [124]:
def reverse_digit(num):
    rev=0
    while num!=0:
        rem=num%10
        rev=rev*10+rem
        num=num//10
    else:
        print("Done")
    return rev
reverse_digit(154)

Done


451

### Exercise 11: Write a program to display all prime numbers within a range

In [112]:
import math 
def prime_num(rang):
    for i in range(1,rang+1):
        j=2
        flag=0
        while j<=int(math.sqrt(i)):
            if i%j==0:
                flag=1
                break
            j+=1
        if flag==0:
            print(i,end=" ")
prime_num(1000)
            

1 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983 991 997 

### Exercise 12: Display Fibonacci series up to 10 terms

In [114]:
num1, num2 = 0, 1

print("Fibonacci sequence:")
for i in range(10):
    print(num1, end="  ")
    res = num1 + num2
    num1 = num2
    num2 = res 

Fibonacci sequence:
0  1  1  2  3  5  8  13  21  34  

### Exercise 13: Find the factorial of a given number

In [123]:
def fact(num):
    if num==0:
        return 1
    return num*fact(num-1)
fact(5)

120

### Exercise 14: Reverse a given integer number

In [126]:
def reverse_digit(num):
    rev=0
    while num!=0:
        rem=num%10
        rev=rev*10+rem
        num=num//10

    return rev
reverse_digit(145)

541

### Exercise 15: Use a loop to display elements from a given list present at odd index positions

In [128]:
list=[10,20,40,30,50,60,90]
for i in range(len(list)):
    if i%2!=0:
        print(f"index: {i} value: {list[i]}")

index: 1 value: 20
index: 3 value: 30
index: 5 value: 60


### Exercise 16: Calculate the cube of all numbers from 1 to a given number

In [134]:
def Cube(Num):
    for i in range(1,Num):
        
        print(f"Cube of {i}={i*i*i}")
Cube(10)

Cube of 1=1
Cube of 2=8
Cube of 3=27
Cube of 4=64
Cube of 5=125
Cube of 6=216
Cube of 7=343
Cube of 8=512
Cube of 9=729


### Exercise 17: Find the sum of the series upto n terms

In [144]:
def Sum(n):
    sum=0
    strg=""
    for i in range(1,n+1):
        strg+=str(i)+"+"
        sum+=i
    return f"{strg[:-1]}={str(sum)}"
n=int(input("Enter Value of N:"))
st=Sum(n)
print(st)

Enter Value of N:10
1+2+3+4+5+6+7+8+9+10=55


In [ ]:
Exercise 18: Print the following pattern
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * 
* * * 
* * 
*

In [148]:
row=int(input("Enter No of Rows"))
for i in range(1,row+1):
    for j in range(i):
        print("*",end=" ")
    print()
for i in range(1,row+1):
    for j in range(row-i):
        print("*",end=" ")
    print()

Enter No of Rows6
* 
* * 
* * * 
* * * * 
* * * * * 
* * * * * * 
* * * * * 
* * * * 
* * * 
* * 
* 



# DAY 3

### Exercise 1: Given two lists create a third list by picking an odd-index element from the first list and even index elements from the second.
* listOne = [3, 6, 9, 12, 15, 18, 21]
* listTwo = [4, 8, 12, 16, 20, 24, 28]
*Output:
** Element at odd-index positions from list one
** [6, 12, 18]
** Element at even-index positions from list two
** [4, 12, 20, 28]
** Printing Final third list
** [6, 12, 18, 4, 12, 20, 28]

In [152]:
listOne = [3, 6, 9, 12, 15, 18, 21]
listTwo = [4, 8, 12, 16, 20, 24, 28]

list_odd=[]
list_even=[]
for i in range(len(listOne)):
    if i%2!=0:
        list_odd.append(listOne[i])
for i in range(len(listTwo)):
    if i%2==0:
        list_even.append(listTwo[i])
ans=list_odd+list_even
ans

[6, 12, 18, 4, 12, 20, 28]

### Exercise 2: Given a list slice it into 3 equal chunks and reverse each chunk
Given:
* sampleList = [11, 45, 8, 23, 14, 12, 78, 45, 89]
* Expected Output:
* Original list  [11, 45, 8, 23, 14, 12, 78, 45, 89]
* Chunk  1 [11, 45, 8]
* After reversing it  [8, 45, 11]
* Chunk  2 [23, 14, 12]
* After reversing it  [12, 14, 23]
* Chunk  3 [78, 45, 89]
* After reversing it  [89, 45, 78]

In [158]:
def Slice_equal_chunks(list1):
    length=len(list1)
    chunks=length//3
    chunk1=list1[:chunks]
    chunk2=list1[chunks:chunks+chunks]
    chunk3=list1[chunks+chunks:]
    print(f"Original List:{list1}")
    print(f"Chunk 1{chunk1}")
    print(f"After reversing it{chunk1[::-1]}")
    print(f"Chunk 2{chunk2}")   
    print(f"After reversing it{chunk2[::-1]}")
    print(f"Chunk 3{chunk3}")   
    print(f"After reversing it {chunk3[::-1]}")
Slice_equal_chunks([11, 45, 8, 23, 14, 12, 78, 45, 89])
    

Original List:[11, 45, 8, 23, 14, 12, 78, 45, 89]
Chunk 1[11, 45, 8]
After reversing it[8, 45, 11]
Chunk 2[23, 14, 12]
After reversing it[12, 14, 23]
Chunk 3[78, 45, 89]
After reversing it [89, 45, 78]


### Exercise 4: Given two sets, Checks if One Set is a subset or superset of another Set. if the subset is found delete all elements from that set
Given:
* firstSet = {27, 43, 34}
* secondSet = {34, 93, 22, 27, 43, 53, 48}
* Expected Output:
* First Set  {57, 83, 29}
* Second Set  {67, 73, 43, 48, 83, 57, 29}

* First set is subset of second set - True
* Second set is subset of First set -  False

* First set is Super set of second set -  False
* Second set is Super set of First set -  True

* First Set  set()
* Second Set  {67, 73, 43, 48, 83, 57, 29

In [159]:
first_set = {27, 43, 34}
second_set = {34, 93, 22, 27, 43, 53, 48}

print("First Set ", first_set)
print("Second Set ", second_set)

print("First set is subset of second set -", first_set.issubset(second_set))
print("Second set is subset of First set - ", second_set.issubset(first_set))

print("First set is Super set of second set - ", first_set.issuperset(second_set))
print("Second set is Super set of First set - ", second_set.issuperset(first_set))

if first_set.issubset(second_set):
    first_set.clear()

if second_set.issubset(first_set):
    second_set.clear()

print("First Set ", first_set)
print("Second Set ", second_set)

First Set  {27, 34, 43}
Second Set  {48, 34, 53, 22, 27, 43, 93}
First set is subset of second set - True
Second set is subset of First set -  False
First set is Super set of second set -  False
Second set is Super set of First set -  True
First Set  set()
Second Set  {48, 34, 53, 22, 27, 43, 93}


### Exercise 5: Given a dictionary get all values from the dictionary and add them to a list but don’t add duplicates
Given:
* speed ={'jan':47, 'feb':52, 'march':47, 'April':44, 'May':52, 'June':53, 'july':54, 'Aug':44, 'Sept':54}
*Output:
*[47, 52, 44, 53, 54]

In [163]:
speed ={'jan':47, 'feb':52, 'march':47, 'April':44, 'May':52, 'June':53, 'july':54, 'Aug':44, 'Sept':54}
speed_list=[]
for i in speed:
    if speed[i] not in speed_list:
        speed_list.append(speed[i])
print(speed_list)     

[47, 52, 44, 53, 54]


# DAY 4

### OOP Exercise 1: Create a Vehicle class with max_speed and mileage instance attributes

In [176]:
class Vehicle:
    def __init__(self,max_speed,mileage):
        self.max_speed=max_speed
        self.mileage=mileage

### OOP Exercise 2: Create a Vehicle class without any variables and methods

In [ ]:
class Vehicle:
    pass

### OOP Exercise 3: Create a child class Bus that will inherit all of the variables and methods of the Vehicle class
Create a Bus object that will inherit all of the variables and methods of the Vehicle class and display it.

In [178]:
class Vehicle:
    def __init__(self,name,max_speed,mileadge):
        self.name=name
        self.mileadge=mileadge
        self.max_speed=max_speed
class Bus(Vehicle):
    pass

In [189]:
B1=Bus("Arya College Chhapri bus",10,20)
print(f"Bus Name    : {B1.name}\nBus Speed   : {B1.max_speed}\nBus mileadge: {B1.mileadge}")

Bus Name    : Arya College Chhapri bus
Bus Speed   : 10
Bus mileadge: 20


### OOP Exercise 4: Class Inheritance
Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.

In [193]:
class Vehicle:
    def __init__(self,name,max_speed,mileadge):
        self.name=name
        self.mileadge=mileadge
        self.max_speed=max_speed
    def Seating_capacity(self,capacity):
        print(f"The Seat capacity of {self.name} is {capacity}")
class Bus(Vehicle):
    pass


In [197]:
B1=Bus("Arya College Chhapri bus",10,20)
B1.Seating_capacity(50)


The Seat capacity of Arya College Chhapri bus is 50


### OOP Exercise 5: Define property that should have the same value for every class instance
Define a class attribute”color” with a default value white. i.e., Every Vehicle should be white.

In [198]:
class Vehicle:
    color="White"
    def __init__(self,name,max_speed,mileadge):
        self.name=name
        self.mileadge=mileadge
        self.max_speed=max_speed
    def Seating_capacity(self,capacity):
        print(f"The Seat capacity of {self.name} is {capacity}")
class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass

In [201]:
B1=Bus("Arya College Bus",120,20)
print(f"Bus name : {B1.name}\nBus max_speed : {B1.max_speed}\nBus mileadge : {B1.mileadge}\nBus Color : {B1.color}")

Bus name : Arya College Bus
Bus max_speed : 120
Bus mileadge : 20
Bus Color : White


In [202]:
C1=Car("RollsRoy",160,40)
print(f"Car name : {C1.name}\nBus max_speed : {C1.max_speed}\nBus mileadge : {C1.mileadge}\nBus Color : {C1.color}")

Car name : RollsRoy
Bus max_speed : 160
Bus mileadge : 40
Bus Color : White


### OOP Exercise 6: Class Inheritance
Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.

Note: The bus seating capacity is 50. so the final fare amount should be 5500. You need to override the fare() method of a Vehicle class in Bus class.

In [229]:
class Vehicle:
    color="White"
    
    def __init__(self,name,mileadge,capacity):
        self.name=name
        self.mileadge=mileadge
        self.capacity=capacity
    def fare(self):
        return self.capacity*100
class Bus(Vehicle):
    def fare(self):
        total_fare = super().fare()
        total_fare += total_fare * 10 / 100
        return total_fare

In [230]:
B1=Bus("Arya College Volvo",30,50)
B1.fare()

5500.0

### OOP Exercise 7: Determine which class a given Bus object belongs to (Check type of an object)


In [6]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)
print(type(School_bus))

<class '__main__.Bus'>


### OOP Exercise 8: Determine if School_bus is also an instance of the Vehicle class 
class Vehicle:
* def __init__(self, name, mileage, capacity):
** self.name = name
** self.mileage = mileage
** self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)

In [4]:
class Vehicle:
    def init(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity
class Bus(Vehicle): 
    pass

School_bus = Bus()
print(isinstance(School_bus,Vehicle))

True


# DAY 5

### Write a program to create a function that takes two arguments, name and age, and print their value.

In [7]:
def func(name,age):
    print(f"Name:{name}\nAge:{age}")

In [8]:
func("Rajesh",22)

Name:Rajesh
Age:22


### Exercise 2: Create a function with variable length of arguments
#### Write a program to create function func1() to accept a variable length of arguments and print their value.

###### Note: Create a function in such a way that we can pass any number of arguments to this function and the function should process them and display each argument’s value.

In [11]:
def func1(*arg):
    for i in arg:
        print(i,end=" ")
func1(45,69,89,50)

45 69 89 50 

### Exercise 3: Return multiple values from a function
##### Write a program to create function calculation() such that it can accept two variables and calculate addition and subtraction. Also, it must return both addition and subtraction in a single return call.
#### Given:


In [12]:
def calculation(a, b):
    # Your Code
    add=a+b
    sub=a-b
    return add,sub

res = calculation(40, 10)
print(res)

(50, 30)


### Exercise 4: Create a function with default argument

In [17]:
def func(sem,name="Rajesh",age=21):
    print(f"Name : {name}\nAge : {age} \nSemester : {sem}")
func(7)

Name : Rajesh
Age : 21 
Semester : 7


### Exercise 5: Create an inner function to calculate the addition in the following way

In [20]:
def func1(num1,num2):
    def add(num1,num2):
        return num1+num2
    print(add(num1,num2))

In [21]:
func1(5,6)

11


### Exercise 7: Assign a different name to function and call it through the new name

In [4]:
def cel_employee(name,age):
    print(f"Name : {name}\nAge : {age}")
cel_employee("Rajesh",22)
cel_big_data=cel_employee
cel_employee("Ranveer Singh Ranawat",22)

Name : Rajesh
Age : 22
Name : Ranveer Singh Ranawat
Age : 22


### Exercise 8: Generate a Python list of all the even numbers between 4 to 30

In [5]:
print(list(range(4, 30, 2)))

[4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


### Exercise 9: Find the largest item from a given list

In [6]:
x = [4, 6, 8, 24, 12, 2]
print(max(x))

24


# DAY 7

#### Exercise 1: From the given dataset print the first and last five rows

In [1]:
import pandas as pd


In [2]:
df=pd.read_csv("Automobile_data.csv")

In [3]:
df.tail(5)

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

### Exercise 2: Clean the dataset and update the CSV file

In [6]:
df = pd.read_csv("Automobile_data.csv", na_values={
'price':["?","n.a"],
'stroke':["?","n.a"],
'horsepower':["?","n.a"],
'peak-rpm':["?","n.a"],
'average-mileage':["?","n.a"]})
print (df)

df.to_csv("Automobile_data.csv")

    index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four        

#### Exercise 3: Find the most expensive car company name

In [7]:
df=df[['company','price']][df.price==df['price'].max()]

In [8]:
df

company    price
35  mercedes-benz  45400.0

### Print All Toyota Cars details

In [21]:
df = pd.read_csv("Automobile_data.csv")
car_Manufacturers = df.groupby('company')
toyotaDf = car_Manufacturers.get_group('toyota')
toyotaDf

Unnamed: 0  index company body-style  wheel-base  length engine-type  \
48          48     66  toyota  hatchback        95.7   158.7         ohc   
49          49     67  toyota  hatchback        95.7   158.7         ohc   
50          50     68  toyota  hatchback        95.7   158.7         ohc   
51          51     69  toyota      wagon        95.7   169.7         ohc   
52          52     70  toyota      wagon        95.7   169.7         ohc   
53          53     71  toyota      wagon        95.7   169.7         ohc   
54          54     79  toyota      wagon       104.5   187.8        dohc   

   num-of-cylinders  horsepower  average-mileage    price  
48             four          62               35   5348.0  
49             four          62               31   6338.0  
50             four          62               31   6488.0  
51             four          62               31   6918.0  
52             four          62               27   7898.0  
53             four          62               27   8778.0  
54              six         156               19  15750.0

### Count total cars per company

In [14]:
df['company'].value_counts()

mercedes-benz    1
Name: company, dtype: int64

### Exercise 6: Find each company’s Higesht price car

In [15]:
car_Manufacturers = df.groupby('company')
priceDf = car_Manufacturers['company','price'].max()
priceDf

C:\Users\erraj\AppData\Local\Temp\ipykernel_20760\1278452937.py:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  priceDf = car_Manufacturers['company','price'].max()


company    price
company                              
mercedes-benz  mercedes-benz  45400.0

### Exercise 7: Find the average mileage of each car making company

In [20]:
df = pd.read_csv("Automobile_data.csv")
car_Manufacturers = df.groupby('company')
mileageDf = car_Manufacturers['company','average-mileage'].mean()
mileageDf

C:\Users\erraj\AppData\Local\Temp\ipykernel_20760\2767902227.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()
C:\Users\erraj\AppData\Local\Temp\ipykernel_20760\2767902227.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  mileageDf = car_Manufacturers['company','average-mileage'].mean()


average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

### Exercise 8: Sort all cars by Price column

In [18]:
carsDf = pd.read_csv("Automobile_data.csv")
carsDf = carsDf.sort_values(by=['price', 'horsepower'], ascending=False)
carsDf.head(5)

Unnamed: 0  index        company   body-style  wheel-base  length  \
35          35     47  mercedes-benz      hardtop       112.0   199.2   
11          11     14            bmw        sedan       103.5   193.8   
34          34     46  mercedes-benz        sedan       120.9   208.1   
46          46     62        porsche  convertible        89.5   168.9   
12          12     15            bmw        sedan       110.0   197.0   

   engine-type num-of-cylinders  horsepower  average-mileage    price  
35        ohcv            eight         184               14  45400.0  
11         ohc              six         182               16  41315.0  
34        ohcv            eight         184               14  40960.0  
46        ohcf              six         207               17  37028.0  
12         ohc              six         182               15  36880.0

### Exercise 9: Concatenate two data frames using the following conditions

In [22]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
carsDf1 = pd.DataFrame.from_dict(GermanCars)

japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
carsDf2 = pd.DataFrame.from_dict(japaneseCars)

carsDf = pd.concat([carsDf1, carsDf2], keys=["Germany", "Japan"])
carsDf


Company   Price
Germany 0         Ford   23845
        1     Mercedes  171995
        2          BMV  135925
        3         Audi   71400
Japan   0       Toyota   29995
        1        Honda   23600
        2       Nissan   61500
        3  Mitsubishi    58900

#### Exercise 10: Merge two data frames using the following condition
Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [23]:
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}
carPriceDf = pd.DataFrame.from_dict(Car_Price)

car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}
carsHorsepowerDf = pd.DataFrame.from_dict(car_Horsepower)

carsDf = pd.merge(carPriceDf, carsHorsepowerDf, on="Company")
carsDf


Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160